### ISSUE TITLE
Twitch.tv

### ISSUE THREAD

**Issue by Kingcox22** [hensm/fx_cast-compat#19] opened 2021-05-16 16:29 UTC
[https://i.imgur.com/w0OrSW9.png](url)

**Comment by hensm** [comment] 2021-05-16 18:00
Duplicate of #6

**Closed as completed by hensm** 2021-05-16 18:00 UTC
Labels: duplicate

**Comment by Kingcox22** [comment] 2021-05-16 18:01
Yea I am sorry I noticed it about a minute ago. Thanks for your work :D

**Comment by hensm** [comment] 2021-05-16 18:07
No worries, thanks!
