### ISSUE TITLE
[compat] <YouTube>

### ISSUE THREAD

**Issue by ghost** [hensm/fx_cast-compat#21] opened 2021-11-20 17:27 UTC
**App name:** 

YouTube

**App URL:**

www.youtube.com/*
**App ID (if possible):**

**Issues:**
Set the appropriate `compat-` label and list any issues here.

Unable to stop casting of video on chromecast

**Error log (if applicable):**

**Comment by hensm** [comment] 2022-03-16 00:33
Duplicate of #10

**Closed as completed by hensm** 2022-03-16 00:33 UTC
Labels: duplicate
